# Sensitive API patterns for taint analysis.
# These lists are used to identify Python builtin/stdlib calls that may indicate malicious behavior.

SENSITIVE_SYSCALL_STRINGS = [
    'shutil.py:<module>.copyfileobj',
    'shutil.py:<module>.copyfile',
    'shutil.py:<module>.copymode',
    'shutil.py:<module>.copystat',
    'shutil.py:<module>.copy',
    'shutil.py:<module>.copy2',
    'shutil.py:<module>.copytree',
    'shutil.py:<module>.rmtree',
    'shutil.py:<module>.move',
    'tempfile.py:<module>.gettempdir',
    'tempfile.py:<module>.NamedTemporaryFile',
    'tempfile.py:<module>.TemporaryFile',
    'pkgutil.py:<module>.find_module',
    'pkgutil.py:<module>.iter_modules',
    'pkgutil.py:<module>.read_code',
    'pkgutil.py:<module>.walk_packages',
    'pkgutil.py:<module>.iter_importer_modules',
    'pkgutil.py:<module>.get_importer',
    'pkgutil.py:<module>.iter_importers',
    'pkgutil.py:<module>.get_loader',
    'pkgutil.py:<module>.find_loader',
    'pkgutil.py:<module>.extend_path',
    'pkgutil.py:<module>.get_data',
    'pkgutil.py:<module>.resolve_name',
    'pkgutil.py:<module>.load_module',
    'pkgutil.py:<module>.is_package',
    'pkgutil.py:<module>.get_code',
    'pkgutil.py:<module>.get_source',
    'pkgutil.py:<module>.get_filename',
    'pkgutil.py:<module>.iter_zipimport_modules',
    'gzip.py:<module>.compress',
    'webbrowser.py:<module>.open',
    'base64.py:<module>.b64encode',
    'base64.py:<module>.b64decode',
    'base64.py:<module>.standard_b64encode',
    'base64.py:<module>.standard_b64decode',
    'base64.py:<module>.urlsafe_b64encode',
    'base64.py:<module>.urlsafe_b64decode',
    'base64.py:<module>.b32encode',
    'base64.py:<module>.b32decode',
    'base64.py:<module>.b32hexencode',
    'base64.py:<module>.b32hexdecode',
    'base64.py:<module>.b16encode',
    'base64.py:<module>.b16decode',
    'base64.py:<module>.a85encode',
    'base64.py:<module>.a85decode',
    'base64.py:<module>.b85encode',
    'base64.py:<module>.b85decode',
    'base64.py:<module>.encode',
    'base64.py:<module>.decode',
    'base64.py:<module>.encodebytes',
    'base64.py:<module>.decodebytes',
    'bisect.py:<module>.bisect_right',
    'warnings.py:<module>.showwarning',
    'warnings.py:<module>.formatwarning',
    'warnings.py:<module>.filterwarnings',
    'warnings.py:<module>.simplefilter',
    'warnings.py:<module>.resetwarnings',
    'warnings.py:<module>.warn',
    'warnings.py:<module>.warn_explicit',
    'subprocess.py:<module>.call',
    'subprocess.py:<module>.check_call',
    'subprocess.py:<module>.check_output',
    'subprocess.py:<module>.run',
    'subprocess.py:<module>.list2cmdline',
    'subprocess.py:<module>.getstatusoutput',
    'subprocess.py:<module>.getoutput',
    'codecs.py:<module>.open',
    'os.py:<module>.copy',
    'os.py:<module>.setdefault',
    'os.py:<module>.makedirs',
    'os.py:<module>.removedirs',
    'os.py:<module>.renames',
    'os.py:<module>.walk',
    'os.py:<module>.fwalk',
    'os.py:<module>.execl',
    'os.py:<module>.execle',
    'os.py:<module>.execlp',
    'os.py:<module>.execlpe',
    'os.py:<module>.execvp',
    'os.py:<module>.execvpe',
    'os.py:<module>.get_exec_path',
    'os.py:<module>.getenv',
    'os.py:<module>.getenvb',
    'os.py:<module>.spawnv',
    'os.py:<module>.spawnve',
    'os.py:<module>.spawnvp',
    'os.py:<module>.spawnvpe',
    'os.py:<module>.spawnl',
    'os.py:<module>.spawnle',
    'os.py:<module>.spawnlp',
    'os.py:<module>.spawnlpe',
    'os.py:<module>.popen',
    'os.py:<module>.fdopen',
    'os.py:<module>.add_dll_directory',
    'os.py:<module>.close',
    'random.py:<module>.seed',
    'random.py:<module>.getstate',
    'random.py:<module>.setstate',
    'random.py:<module>.randbytes',
    'random.py:<module>.randrange',
    'random.py:<module>.randint',
    'random.py:<module>.choice',
    'random.py:<module>.shuffle',
    'random.py:<module>.sample',
    'random.py:<module>.choices',
    'random.py:<module>.uniform',
    'random.py:<module>.triangular',
    'random.py:<module>.normalvariate',
    'random.py:<module>.gauss',
    'random.py:<module>.lognormvariate',
    'random.py:<module>.expovariate',
    'random.py:<module>.vonmisesvariate',
    'random.py:<module>.gammavariate',
    'random.py:<module>.betavariate',
    'random.py:<module>.paretovariate',
    'random.py:<module>.weibullvariate',
    'random.py:<module>.random',
    'random.py:<module>.getrandbits',
    'platform.py:<module>.uname',
    'platform.py:<module>.system',
    'platform.py:<module>.node',
    'platform.py:<module>.release',
    'platform.py:<module>.version',
    'platform.py:<module>.machine',
    'platform.py:<module>.processor',
    'secrets.py:<module>.randbelow',
    'secrets.py:<module>.token_bytes',
    'secrets.py:<module>.token_hex',
    'secrets.py:<module>.token_urlsafe',
    'getpass.py:<module>.getuser',
    'pty.py:<module>.spawn',
    'socket.py:<module>.getfqdn',
    'socket.py:<module>.create_connection',
    'socket.py:<module>.create_server',
    'socket.py:<module>.getaddrinfo',
    'uuid.py:<module>.getnode',
    'uuid.py:<module>.uuid4',
    're.py:<module>.scan',
    're.py:<module>.match',
    're.py:<module>.fullmatch',
    're.py:<module>.search',
    're.py:<module>.sub',
    're.py:<module>.subn',
    're.py:<module>.split',
    're.py:<module>.findall',
    're.py:<module>.finditer',
    're.py:<module>.compile',
    're.py:<module>.purge',
    're.py:<module>.template',
    're.py:<module>.escape',
]

SENSITIVE_FUNCTIONS_ADDITIONAL = [
    # Network related
    "socket.py:<module>.socket", "socket.py:<module>.socket.<returnValue>.connect",
    "socket.py:<module>.socket.<returnValue>.recv",
    "socket.py:<module>.socket.<returnValue>.send", "socket.py:<module>.gethostname",
    "socket.py:<module>.socket.<returnValue>.bind",
    "socket.py:<module>.socket.<returnValue>.listen", "socket.py:<module>.socket.<returnValue>.accept",
    "socket.py:<module>.gethostbyname",
    "ssl.py:<module>.wrap_socket", "ssl.py:<module>.create_default_context",
    "multiprocessing.connection:Listener",
    "smtplib.py:<module>.SMTP", "smtplib.py:<module>.SMTP_SSL",
    "ftplib.py:<module>.FTP", "ftplib.py:<module>.FTP_TLS",
    "http.client.py:<module>.HTTPConnection",
    "requests.py:<module>.get", "requests.py:<module>.post",
    "wget.py:<module>.download",
    "webbrowser.py:<module>.open", "urllib.py:<module>.urlopen",
    "websocket.py:<module>.create_connection",
    "urllib/request.py:<module>.urlopen",
    # Crypto
    "json.py:<module>.dumps.<returnValue>.encode", "json.py:<module>.loads",
    "base64.py:<module>.b64decode",
    "cryptography/fernet.py:<module>.Fernet.generate_key",
    "cryptography/fernet.py:<module>.Fernet.encrypt",
    "cryptography/fernet.py:<module>.Fernet.decrypt",
    "secrets.py:<module>.token_hex",
    "pyAesCrypt.py:<module>.encryptFile", "pyAesCrypt.py:<module>.decryptFile",
    "win32crypt.py:<module>.CryptUnprotectData",
    "hashlib.py:<module>.sha256", "hashlib.py:<module>.md5", "hashlib.py:<module>.sha1",
    # System info
    "os.py:<module>.getenv", "os.py:<module>.environ", "os.py:<module>.system",
    "os.py:<module>.getlogin",
    "platform.py:<module>.uname", "platform.py:<module>.platform", "platform.py:<module>.machine",
    "getpass.py:<module>.getuser",
    # File operations
    "shutil.py:<module>.copyfile", "shutil.py:<module>.move", "shutil.py:<module>.rmtree",
    "os.py:<module>.makedirs", "os.py:<module>.walk", "os.py:<module>.chdir",
    "os.py:<module>.remove", "os.py:<module>.rename", "os.py:<module>.getcwd",
    "os.py:<module>.listdir", "os.py:<module>.stat",
    "__builtin.open", "__builtin.input",
    "importlib.py:<module>.<member>(machinery).SourceFileLoader.__init__",
    "importlib.py:<module>.<member>(machinery).SourceFileLoader.get_data",
    "glob.py:<module>.glob",
    # Process
    "subprocess.py:<module>.call", "os.py:<module>.getuid",
    "subprocess.py:<module>.Popen.__init__", "subprocess.py:<module>.getoutput",
    "subprocess.py:<module>.run", "subprocess.py:<module>.check_output",
    "threading.py:<module>.Thread", "threading.py:<module>.Thread.__init__",
    "threading.py:<module>.Thread.start",
    "pynput.py:<module>.keyboard.Listener",
    "__builtin.exec", "__builtin.eval",
    "os.py:<module>.popen",
    # Keylogger
    "keyboard.py:<module>.on_release", "keyboard.py:<module>.on_press",
    "keyboard.py:<module>.block_key",
    # Database
    "sqlite3.py:<module>.connect",
    # Registry
    "winreg.py:<module>.OpenKey", "winreg.py:<module>.CreateKey",
]
